// Load environment variables from root .env first, then server/.env (fallback)
// Already-set env vars are preserved
try {
  const dotenv = require('dotenv');
  const path = require('path');
  // Load server/.env first (local dev overrides) then root .env if missing values
  dotenv.config({ path: path.resolve(__dirname, '.env'), override: true });
  dotenv.config({ path: path.resolve(__dirname, '../.env'), override: false });
  console.log('[ENV] Final MONGO_URI source prioritized from server/.env');
} catch (e) {
  // dotenv optional
}
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const path = require('path');
const fs = require('fs'); // Required for checking/creating directories

// Import routes
const authRoutes = require('./routes/auth');
const explainRoutes = require('./routes/explain');
const historyRoutes = require('./routes/history');

const app = express();
const PORT = process.env.PORT || 5000;
const HOST = process.env.HOST || '0.0.0.0';

// Ensure public/audio directory exists for TTS output
const audioPublicDir = path.join(__dirname, 'public/audio');
if (!fs.existsSync(audioPublicDir)) {
  fs.mkdirSync(audioPublicDir, { recursive: true });
}

// Middleware
app.use(cors()); // Enable CORS for all origins (adjust for production)
app.use(express.json()); // Parse JSON request bodies
app.use(express.urlencoded({ extended: true })); // Parse URL-encoded request bodies

// Serve static files (for audio files generated by TTS)
app.use('/audio', express.static(path.join(__dirname, 'public/audio')));

// =============================================
// DATABASE CONNECTION - CURRENTLY DISABLED
// =============================================
// MongoDB connection is commented out - server runs without database
// Users can upload code and get AI explanations without DB
// History saving and authentication are disabled

/* 
// Database Connection
// Normalize MONGO_URI to ensure database name present
let mongoUri = process.env.MONGO_URI || '';
if (/mongodb\+srv:/.test(mongoUri) && !/mongodb\.net\/[^?]+/.test(mongoUri)) {
  // Inject default database 'runthru' if none specified before query string
  mongoUri = mongoUri.replace(/(mongodb\+srv:\/\/[^\/]+)(\/?)(\?)/, '$1/runthru$3');
}
if (/mongodb:\/\//.test(mongoUri) && !/mongodb:\/\/[^\/]+\/[^?]+/.test(mongoUri)) {
  mongoUri = mongoUri.replace(/(mongodb:\/\/[^\/]+)(\/?)(\?)/, '$1/runthru$3');
}
console.log('[ENV] Using MONGO_URI:', (mongoUri || '').replace(/:[^:]*@/,'://****:****@'));

async function connectMongo(primaryUri) {
  try {
    await mongoose.connect(primaryUri, {
      serverSelectionTimeoutMS: 8000,
      socketTimeoutMS: 60000,
      maxPoolSize: 10,
      minPoolSize: 2,
      retryWrites: true,
    });
    console.log('✅ Atlas MongoDB connected');
  } catch (err) {
    console.error('❌ Atlas MongoDB connection error:', err.message);
    console.error('⚠️ Server will continue WITHOUT database (history saving disabled)');
    console.error('📋 To enable history/auth, whitelist this IP in Atlas Network Access');
  }
}

connectMongo(mongoUri);

// MongoDB connection event listeners
mongoose.connection.on('connected', () => {
  console.log('✅ Mongoose connected to MongoDB');
});

mongoose.connection.on('disconnected', () => {
  console.warn('⚠️  Mongoose disconnected from MongoDB');
});

mongoose.connection.on('error', (err) => {
  console.error('❌ MongoDB connection error:', err);
});
*/

console.log('⚠️ MongoDB is DISABLED - Server running without database');
console.log('✅ Code explanations work without auth or database');

// API Routes
app.use('/api/auth', authRoutes);
app.use('/api/explain', explainRoutes);
app.use('/api/history', historyRoutes);

// Basic health check route
app.get('/', (req, res) => {
  res.send('RunThru Backend API is running!');
});

// Error handling middleware
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).send('Something broke on the server!');
});

// Start the server
app.listen(PORT, HOST, () => {
  console.log(`Server running on http://${HOST}:${PORT}`);
});

